"""Slicer parser gate: each format + the manual fallback + unknown -> error."""
import pytest

from app import slicer

PRUSA = """
; generated by PrusaSlicer 2.7.1
; estimated printing time (normal mode) = 1h 48m 30s
; filament used [mm] = 7421.5
; filament used [g] = 22.13
"""

CURA = """
;FLAVOR:Marlin
;TIME:6480
;Filament used: 7.42069m
;Generated with Cura_SteamEngine
"""

BAMBU = """
; HEADER_BLOCK_START
; BambuStudio 1.8.0
; model printing time: 1h 52m 5s; total estimated time: 2h 1m 0s
; total filament weight [g] : 23.5
"""

MANUAL = """
time: 1h 48m
material: 22 g
"""


def test_prusaslicer():
    e = slicer.parse(PRUSA)
    assert e.slicer_name == "PrusaSlicer"
    assert e.est_time_seconds == 6510            # 1h48m30s
    assert e.est_material_qty == pytest.approx(22.13)
    assert e.est_material_unit == "g"


def test_cura():
    e = slicer.parse(CURA)
    assert e.slicer_name == "Cura"
    assert e.est_time_seconds == 6480
    assert e.est_material_qty == pytest.approx(7.42069)
    assert e.est_material_unit == "m"            # Cura reports length


def test_bambu():
    e = slicer.parse(BAMBU)
    assert e.slicer_name == "Bambu Studio"
    assert e.est_time_seconds == 6725            # 1h52m5s
    assert e.est_material_qty == pytest.approx(23.5)
    assert e.est_material_unit == "g"


def test_manual_fallback():
    e = slicer.parse(MANUAL)
    assert e.slicer_name == "manual"
    assert e.est_time_seconds == 6480
    assert e.est_material_qty == pytest.approx(22.0)
    assert e.est_material_unit == "g"


def test_unknown_raises():
    with pytest.raises(slicer.SlicerParseError):
        slicer.parse("this is just an STL header, no summary here")
