"""Phase 4 API gate: auth + role-gating, file-version chain + slicer parse, transition
endpoints, inventory warnings, on_done same-transaction decrement (+ reconcile), and
notification generation."""
from datetime import datetime, timezone

import pytest

from app.audit import reconcile_all
from app.enums import InventoryReason, MaterialKind, PrinterStatus, ProcessType
from app.models import InventoryTxn, Material, Printer

PRUSA_GCODE = (
    "; generated by PrusaSlicer 2.7.1\n"
    "; estimated printing time (normal mode) = 1h 48m 30s\n"
    "; filament used [g] = 22.0\n"
)


# ----------------------------------------------------------------- fixtures/helpers
def _add_printer_and_petg(api, *, qty=200.0, reorder=100.0):
    m = Material(kind=MaterialKind.filament, spec="PETG", unit="g",
                 qty_remaining=qty, reorder_threshold=reorder)
    api.db.add(m)
    api.db.flush()
    api.db.add(InventoryTxn(material_id=m.id, delta=qty, reason=InventoryReason.restock,
                            at=datetime.now(timezone.utc)))
    p = Printer(name="MK4", process=ProcessType.FDM, status=PrinterStatus.idle,
                build_volume_x=250, build_volume_y=210, build_volume_z=220,
                loaded_material=m, capabilities={})
    api.db.add(p)
    api.db.commit()
    return p, m


def _create_ticket(api, headers, *, summary=PRUSA_GCODE, material="PETG", process="FDM", bbox=(40, 40, 20)):
    r = api.client.post(
        "/api/tickets", headers=headers,
        data={"title": "bracket", "target_process": process, "priority": "normal",
              "material_pref": material, "bbox_x": bbox[0], "bbox_y": bbox[1], "bbox_z": bbox[2]},
        files={"file": ("model.gcode", summary.encode(), "text/plain")},
    )
    assert r.status_code == 200, r.text
    return r.json()


# ----------------------------------------------------------------------- auth
def test_auth_happy_path(api):
    h = api.login("op", "op-pw")
    me = api.client.get("/api/auth/me", headers=h)
    assert me.status_code == 200 and me.json()["role"] == "operator"


def test_auth_rejects_bad_creds_and_missing_token(api):
    assert api.client.post("/api/auth/login", json={"username": "op", "password": "wrong"}).status_code == 401
    assert api.client.get("/api/auth/me").status_code == 401


# --------------------------------------------------------- slicer parse + file chain
def test_upload_parses_slicer_estimate(api):
    rq = api.login("rq", "rq-pw")
    t = _create_ticket(api, rq)
    fv = t["file_versions"][0]
    assert fv["slicer_name"] == "PrusaSlicer"
    assert fv["est_time_seconds"] == 6510
    assert fv["est_material_qty"] == pytest.approx(22.0)
    assert fv["estimate_label"] == "slicer est."


def test_file_version_chain(api):
    rq = api.login("rq", "rq-pw")
    t = _create_ticket(api, rq)
    tid = t["id"]
    r = api.client.post(f"/api/tickets/{tid}/files", headers=rq,
                        files={"file": ("v2.gcode", PRUSA_GCODE.encode(), "text/plain")})
    assert r.status_code == 200 and r.json()["version_no"] == 2
    full = api.client.get(f"/api/tickets/{tid}", headers=rq).json()
    assert [fv["version_no"] for fv in full["file_versions"]] == [1, 2]
    assert full["current_file_version_id"] == r.json()["id"]   # newest is current


# ------------------------------------------------------------------- role-gating
def test_role_gating(api):
    rq = api.login("rq", "rq-pw")
    rq2 = api.login("rq2", "rq2-pw")
    # requester cannot see operator surfaces
    assert api.client.get("/api/schedule", headers=rq).status_code == 403
    assert api.client.get("/api/materials", headers=rq).status_code == 403
    assert api.client.post("/api/builds/1/advance", headers=rq, json={"to_stage": "qc"}).status_code == 403
    # requester cannot read another requester's ticket
    t = _create_ticket(api, rq)
    assert api.client.get(f"/api/tickets/{t['id']}", headers=rq2).status_code == 403
    # operator can
    op = api.login("op", "op-pw")
    assert api.client.get(f"/api/tickets/{t['id']}", headers=op).status_code == 200


# ------------------------------------------------------ inventory warnings
def test_inventory_warnings(api):
    op = api.login("op", "op-pw")
    _add_printer_and_petg(api, qty=40.0, reorder=150.0)   # 40 < 150 -> low stock
    w = api.client.get("/api/inventory/warnings", headers=op)
    assert w.status_code == 200
    kinds = {x["kind"] for entry in w.json() for x in entry["warnings"]}
    assert "low_stock" in kinds


# ---------------------- end-to-end: confirm -> advance to done -> decrement + notify
def test_done_decrements_material_in_one_transaction_and_notifies(api):
    op = api.login("op", "op-pw")
    rq = api.login("rq", "rq-pw")
    printer, petg = _add_printer_and_petg(api, qty=200.0, reorder=100.0)

    # requester submits + queues the job
    t = _create_ticket(api, rq)
    job_id = t["jobs"][0]["id"]
    assert api.client.post(f"/api/jobs/{job_id}/queue", headers=rq).status_code == 200

    # operator sees a proposal and confirms it
    view = api.client.get("/api/schedule", headers=op).json()
    prop = next(p for p in view["proposals"] if p["printer_id"] == printer.id)
    assert job_id in prop["job_ids"]
    confirmed = api.client.post("/api/schedule/confirm", headers=op,
                                json={"printer_id": printer.id, "job_ids": [job_id]})
    assert confirmed.status_code == 200
    build_id = confirmed.json()["id"]
    assert confirmed.json()["current_stage"] == "printing"

    # operator walks FDM to done
    for to in ("support_removal", "qc", "done"):
        r = api.client.post(f"/api/builds/{build_id}/advance", headers=op, json={"to_stage": to})
        assert r.status_code == 200, r.text
    assert r.json()["status"] == "completed"

    # material decremented by the slicer estimate (22g), in the same transaction
    mat = api.client.get(f"/api/materials/{petg.id}", headers=op).json()
    assert mat["qty_remaining"] == pytest.approx(178.0)     # 200 - 22
    assert reconcile_all(api.db) == []                       # no desync

    # requester got started + ready-for-pickup notifications
    inbox = api.client.get("/api/notifications", headers=rq).json()
    kinds = {n["kind"] for n in inbox}
    assert "started" in kinds and "ready_for_pickup" in kinds


def test_invalid_transition_returns_409(api):
    op = api.login("op", "op-pw")
    rq = api.login("rq", "rq-pw")
    printer, _ = _add_printer_and_petg(api)
    t = _create_ticket(api, rq)
    job_id = t["jobs"][0]["id"]
    api.client.post(f"/api/jobs/{job_id}/queue", headers=rq)
    confirmed = api.client.post("/api/schedule/confirm", headers=op,
                                json={"printer_id": printer.id, "job_ids": [job_id]})
    build_id = confirmed.json()["id"]
    # printing -> qc skips support_removal
    r = api.client.post(f"/api/builds/{build_id}/advance", headers=op, json={"to_stage": "qc"})
    assert r.status_code == 409 and "printing -> qc" in r.json()["detail"]


def test_per_job_reject_notifies_and_overrides(api):
    op = api.login("op", "op-pw")
    rq = api.login("rq", "rq-pw")
    printer, _ = _add_printer_and_petg(api)
    t = _create_ticket(api, rq)
    job_id = t["jobs"][0]["id"]
    api.client.post(f"/api/jobs/{job_id}/queue", headers=rq)
    api.client.post("/api/schedule/confirm", headers=op,
                    json={"printer_id": printer.id, "job_ids": [job_id]})
    r = api.client.post(f"/api/jobs/{job_id}/reject", headers=op, json={"note": "warped"})
    assert r.status_code == 200 and r.json()["status"] == "qc_rejected"
    inbox = api.client.get("/api/notifications", headers=rq).json()
    assert any(n["kind"] == "failed" for n in inbox)
