"""core schema — Part III data model

Build/Job split, FileVersion chain, append-only StageEvent + InventoryTxn, and the
mutable convenience columns guarded by the reconcile check (see app/audit.py).

Enum types are shared across tables (e.g. process_type on printers/tickets/builds). On
Postgres the type is created once and reused; the explicit drops in downgrade make the
migration cleanly reversible. Generic sa.Enum keeps the SQLite local-dev path working
(it renders as VARCHAR + CHECK there, no CREATE TYPE).

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-04
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Named enum types, single-sourced so create/drop stay in sync.
_ENUM_TYPES = (
    "material_kind", "user_role", "process_type", "printer_status", "priority",
    "build_status", "queue_state", "job_terminal_status", "qc_outcome",
    "drying_state", "inventory_reason", "notification_kind",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('filament', 'resin', 'powder', 'agent', name='material_kind'), nullable=False),
    sa.Column('spec', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('qty_remaining', sa.Float(), nullable=False),
    sa.Column('reorder_threshold', sa.Float(), nullable=True),
    sa.Column('lot', sa.String(length=64), nullable=True),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('drying_state', sa.Enum('dry', 'needs_drying', 'drying', name='drying_state'), nullable=True),
    sa.Column('virgin_qty', sa.Float(), nullable=True),
    sa.Column('used_qty', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('operator', 'requester', name='user_role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('process', sa.Enum('FDM', 'SLA', 'SLS', 'MJF', name='process_type'), nullable=False),
    sa.Column('status', sa.Enum('idle', 'printing', 'down', 'maintenance', name='printer_status'), nullable=False),
    sa.Column('build_volume_x', sa.Float(), nullable=False),
    sa.Column('build_volume_y', sa.Float(), nullable=False),
    sa.Column('build_volume_z', sa.Float(), nullable=False),
    sa.Column('loaded_material_id', sa.Integer(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loaded_material_id'], ['materials.id'], name=op.f('fk_printers_loaded_material_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_printers'))
    )
    op.create_index(op.f('ix_printers_name'), 'printers', ['name'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_process', sa.Enum('FDM', 'SLA', 'SLS', 'MJF', name='process_type'), nullable=False),
    sa.Column('material_pref', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'normal', 'low', name='priority'), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('current_file_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_file_version_id'], ['file_versions.id'], name='fk_tickets_current_file_version', use_alter=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_tickets_requester_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('process', sa.Enum('FDM', 'SLA', 'SLS', 'MJF', name='process_type'), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('current_stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('running', 'on_hold', 'failed', 'cancelled', 'completed', name='build_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_builds_material_id_materials')),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], name=op.f('fk_builds_printer_id_printers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_builds'))
    )
    op.create_table('file_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('blob_key', sa.String(length=512), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('slicer_name', sa.String(length=64), nullable=True),
    sa.Column('est_time_seconds', sa.Integer(), nullable=True),
    sa.Column('est_material_qty', sa.Float(), nullable=True),
    sa.Column('est_material_unit', sa.String(length=8), nullable=True),
    sa.Column('bbox_x', sa.Float(), nullable=True),
    sa.Column('bbox_y', sa.Float(), nullable=True),
    sa.Column('bbox_z', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_file_versions_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_versions')),
    sa.UniqueConstraint('ticket_id', 'version_no', name='ticket_version_unique')
    )
    op.create_table('inventory_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('reason', sa.Enum('restock', 'consume', 'adjust', name='inventory_reason'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_inventory_txns_actor_id_users')),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], name=op.f('fk_inventory_txns_build_id_builds')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_inventory_txns_material_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_txns'))
    )
    op.create_index(op.f('ix_inventory_txns_at'), 'inventory_txns', ['at'], unique=False)
    op.create_index(op.f('ix_inventory_txns_material_id'), 'inventory_txns', ['material_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('file_version_id', sa.Integer(), nullable=True),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('queue_state', sa.Enum('submitted', 'queued', 'scheduled', name='queue_state'), nullable=False),
    sa.Column('terminal_status', sa.Enum('failed', 'qc_rejected', 'cancelled', name='job_terminal_status'), nullable=True),
    sa.Column('fail_reason', sa.String(length=255), nullable=True),
    sa.Column('qc_outcome', sa.Enum('pending', 'passed', 'failed', name='qc_outcome'), nullable=True),
    sa.Column('allocated_qty', sa.Float(), nullable=True),
    sa.Column('allocated_unit', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], name=op.f('fk_jobs_build_id_builds')),
    sa.ForeignKeyConstraint(['file_version_id'], ['file_versions.id'], name=op.f('fk_jobs_file_version_id_file_versions')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_jobs_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('started', 'failed', 'ready_for_pickup', 'on_hold', name='notification_kind'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_notifications_job_id_jobs')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_notifications_ticket_id_tickets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('from_stage', sa.String(length=32), nullable=True),
    sa.Column('to_stage', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('build_id IS NOT NULL OR job_id IS NOT NULL', name=op.f('ck_stage_events_event_targets_something')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_stage_events_actor_id_users')),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], name=op.f('fk_stage_events_build_id_builds')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_stage_events_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_events'))
    )
    op.create_index(op.f('ix_stage_events_at'), 'stage_events', ['at'], unique=False)
    op.create_index(op.f('ix_stage_events_build_id'), 'stage_events', ['build_id'], unique=False)
    op.create_index(op.f('ix_stage_events_job_id'), 'stage_events', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_events_job_id'), table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_build_id'), table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_at'), table_name='stage_events')
    op.drop_table('stage_events')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_inventory_txns_material_id'), table_name='inventory_txns')
    op.drop_index(op.f('ix_inventory_txns_at'), table_name='inventory_txns')
    op.drop_table('inventory_txns')
    op.drop_table('file_versions')
    op.drop_table('builds')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_printers_name'), table_name='printers')
    op.drop_table('printers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('materials')
    # ### end Alembic commands ###

    # Drop the PG enum types so the migration is cleanly reversible (no-op on SQLite).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for type_name in _ENUM_TYPES:
            op.execute(f'DROP TYPE IF EXISTS {type_name}')
